// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package sessionlatency

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type probeAcceptArgs struct {
	_             structs.HostLayout
	UpeerSockaddr uint64
	UpeerAddrlen  uint64
}

// loadProbe returns the embedded CollectionSpec for probe.
func loadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probe: %w", err)
	}

	return spec, err
}

// loadProbeObjects loads probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probeObjects
//	*probePrograms
//	*probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeSpecs struct {
	probeProgramSpecs
	probeMapSpecs
	probeVariableSpecs
}

// probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeProgramSpecs struct {
	TraceEnterAccept4     *ebpf.ProgramSpec `ebpf:"trace_enter_accept4"`
	TraceEnterWrite       *ebpf.ProgramSpec `ebpf:"trace_enter_write"`
	TraceEnterWritev      *ebpf.ProgramSpec `ebpf:"trace_enter_writev"`
	TraceExitAccept4      *ebpf.ProgramSpec `ebpf:"trace_exit_accept4"`
	TraceExitWrite        *ebpf.ProgramSpec `ebpf:"trace_exit_write"`
	TraceExitWritev       *ebpf.ProgramSpec `ebpf:"trace_exit_writev"`
	TraceSchedProcessExec *ebpf.ProgramSpec `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit *ebpf.ProgramSpec `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork *ebpf.ProgramSpec `ebpf:"trace_sched_process_fork"`
	TraceTtyWrite         *ebpf.ProgramSpec `ebpf:"trace_tty_write"`
}

// probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeMapSpecs struct {
	Events          *ebpf.MapSpec `ebpf:"events"`
	InflightAccepts *ebpf.MapSpec `ebpf:"inflight_accepts"`
	InflightWrites  *ebpf.MapSpec `ebpf:"inflight_writes"`
}

// probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeVariableSpecs struct {
}

// probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeObjects struct {
	probePrograms
	probeMaps
	probeVariables
}

func (o *probeObjects) Close() error {
	return _ProbeClose(
		&o.probePrograms,
		&o.probeMaps,
	)
}

// probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeMaps struct {
	Events          *ebpf.Map `ebpf:"events"`
	InflightAccepts *ebpf.Map `ebpf:"inflight_accepts"`
	InflightWrites  *ebpf.Map `ebpf:"inflight_writes"`
}

func (m *probeMaps) Close() error {
	return _ProbeClose(
		m.Events,
		m.InflightAccepts,
		m.InflightWrites,
	)
}

// probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeVariables struct {
}

// probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probePrograms struct {
	TraceEnterAccept4     *ebpf.Program `ebpf:"trace_enter_accept4"`
	TraceEnterWrite       *ebpf.Program `ebpf:"trace_enter_write"`
	TraceEnterWritev      *ebpf.Program `ebpf:"trace_enter_writev"`
	TraceExitAccept4      *ebpf.Program `ebpf:"trace_exit_accept4"`
	TraceExitWrite        *ebpf.Program `ebpf:"trace_exit_write"`
	TraceExitWritev       *ebpf.Program `ebpf:"trace_exit_writev"`
	TraceSchedProcessExec *ebpf.Program `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit *ebpf.Program `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork *ebpf.Program `ebpf:"trace_sched_process_fork"`
	TraceTtyWrite         *ebpf.Program `ebpf:"trace_tty_write"`
}

func (p *probePrograms) Close() error {
	return _ProbeClose(
		p.TraceEnterAccept4,
		p.TraceEnterWrite,
		p.TraceEnterWritev,
		p.TraceExitAccept4,
		p.TraceExitWrite,
		p.TraceExitWritev,
		p.TraceSchedProcessExec,
		p.TraceSchedProcessExit,
		p.TraceSchedProcessFork,
		p.TraceTtyWrite,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfeb.o
var _ProbeBytes []byte
